#fdfs:
#  soTimeout: 1500
#  connectTimeout: 600
#  thumbImage:             #缩略图生成参数
#    width: 150
#    height: 150
#  trackerList:            #TrackerList参数,支持多个
#    - 172.16.1.155:22122
fdfs:
  connect-timeout: 601
  pool:
    jmx-enabled: false
  so-timeout: 1501
  thumb-image:
    height: 150
    width: 125
  tracker-list: 172.16.1.155:22122
#=================================================================================
# 自定义参数相关配置


#=================================================================================